### ISSUE TITLE
Is the attribute matrix an adjacency matrix?

### ISSUE THREAD

**Issue by xdlequ** [cszhangzhen/ANRL#1]
Hello, your thoughts make me refreshed. I am very curious about reading the article. What is the attribute information you have proposed? After the research of the code, is it the adjacency matrix corresponding to the network?

**Comment by cszhangzhen** [comment]
Hi, the attribute information we used is not adjacent matrix. We use node features as input.

Since we are embedding attributed information network, in this setting, nodes are associated with features, i.e., bag-of-words features in citation networks or age, gender, education information in social networks. 
For plain information network, the node features is not available. Actually, you can treat adjacent matrix as nodes features.  Our model is still applicable in this scenario.
